style = "yas"
always_use_return = true
indent = 4
margin = 100
always_for_in = true
remove_extra_newlines = true
short_to_long_function_def = true
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = true
format_docstrings = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
