name = "JuliaReachDevDocs"
uuid = "bdb38ff1-04af-56c0-89d5-731474b8680c"
authors = ["mforets <mforets@gmail.com>"]
version = "0.1.0"

[deps]
# add strict dependencies here

[compat]
# add compatibility restrictions for dependencies here
julia = "1"

[extras]
# add optional dependencies here

[targets]
test = ["Test"]
